/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
	export interface GlobalComponents {
		Navbar: typeof import('./src/components/Navbar.vue')['default'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
		Sidebar: typeof import('./src/components/Sidebar.vue')['default'];
		SpaceList: typeof import('./src/components/SpaceList.vue')['default'];
		WikiDocumentList: typeof import('./src/components/WikiDocumentList.vue')['default'];
		WikiEditor: typeof import('./src/components/WikiEditor.vue')['default'];
		WikiEditorWrapper: typeof import('./src/components/WikiEditorWrapper.vue')['default'];
	}
}
